name: Generate Terraform README docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '*.md'
      - '.github/workflows/documentation.yml'

permissions: {}

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@62a6cc597a9a2ee6953471d4c9cc1668c66ebf36 # v1.0.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
